#!/usr/bin/env bash
#
# Displaying rollouts metadata
#
# Author: lovetravelsfaster
# Date: 2025-12-01
# License: MIT

SITE="${1:-}"

rollout_log="/var/log/sites/$SITE/rollout_log.txt"

ssh deploy@lakelabs bash -s -- "$rollout_log" < read-rollout-log