#!/usr/bin/env bash
#
# Displaying releases metadata
# to pick which release to rollout
#
# Author: lovetravelsfaster
# Date: 2025-12-01
# License: MIT

# Strict mode
set -euo pipefail

# Helper functions like check_arg_number, check_site_config, colors, etc.
source "$(dirname "$0")/helpers"

SITE="$1"

# Make sure exact number of args is good, otherwise exit 1
check_arg_number 1 "$#" "$0"

# Site config
source "$(dirname "$0")/site-configs/$SITE"

# Check that loaded site-config has all vars set otherwise exit 1
check_site_config

release_log="/var/log/sites/$SITE_NAME/release_log.txt"

ssh deploy@"$HOST" bash -s -- "$release_log" < read-release-log

printf "===============\n"

ssh deploy@"$HOST" bash -s -- "$SITE" < read-environment-symlinks