#!/usr/bin/env bash
#
# Displaying releases metadata
# to pick which release to rollout
#
# Author: lovetravelsfaster
# Date: 2025-12-01
# License: MIT

SITE="${1:-}"

release_log="/srv/www/$SITE/releases/release_log.txt"

ssh deploy@lakelabs bash -s -- "$release_log" < read-release-log

printf "===============\n"

ssh deploy@lakelabs bash -s -- "$SITE" < read-environment-symlinks